name: bazinga
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  firebase_storage: ^3.1.5
  flare_flutter: any
  google_fonts: any
  google_sign_in: any
  nima: any
  geolocator: any
  share: any
  intl: any
  qr_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/flares/
    - assets/images/